version: '3'
services:
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /usr/src/app/node_modules
      - ./server:/usr/src/app
    env_file:
      - ./server/.env
    ports:
      - "5000:5000"
    networks:
      - mern-app
    depends_on:
      - mongo
  client:
    stdin_open: true
    build: 
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /usr/src/app/node_modules
      - ./client:/usr/src/app
    ports: 
      - "3000:3000"
    networks:
      - mern-app
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: midstacks
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
    
